# Generated by Django 4.2.13 on 2024-05-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
